### ISSUE TITLE
Integration with readthedocs.org docs?

### ISSUE THREAD

**Issue by mikesname** [EHRI/manuals#5]
I'm using a readthedocs.org site for portal-related documentation here:

http://documentation.ehri-project.eu/

Currently it's user-facing stuff, but I'll add the technical/dev docs too in the near future.

Could we possibly integrate these manuals with that site? Ideally via reStructured text, but if need be just as PDF downloads.

@lindareijnhoudt  @LeenartsE

**Comment by lindareijnhoudt** [comment]
or the other way around? point here to the github/ehri/manuals page?

**Comment by mikesname** [comment]
I've added links to this repository from there. Couple of questions:

- how are these PDFs currently generated? Word?
- there's a broken link to readthedocs.org on the MPT README? Does this site actually exist there or not yet implemented?

**Comment by lindareijnhoudt** [comment]
http://rspub-gui.readthedocs.io/en/latest/rst/rsgui.introduction.html

was a problem with the markdown link, so i repaired it

**Comment by mikesname** [comment]
I've added that as a sub-project to the other readthedocs site so it serves from the same domain:

http://documentation.ehri-project.eu/projects/rspub-gui/en/latest/

Let me know if that's a problem. I'll try and refashion the main doc index to look a bit more integrated.
